DEV-1409 add queue name and consumer tag to startup logging
viaacode/vrt-events-essence pull request #16
Opened 2021-02-12 08:14 UTC by DriesDD

Log now looks something like this:
```
INFO     app.app:app.py:497 Waiting for messages on queue mock_queue...
INFO     app.app:app.py:499 Consumer tag is: <MagicMock name='RabbitClient().listen()' id='140594156496640'>...
```
Added a new `test_startup_logs` test event in `test_app.py`, which tests if these messages are logged. To manually also confirm the validity of the type and values of `queue_name` and `consumer_tag` shown in the logs, you can make the test fail to see the logs in the pytest error output.

2021-02-12 09:40 UTC, DriesDD commented
Retry DeepCode

2021-02-19 14:11 UTC, RudolfDG commented on app/services/rabbit.py
> +        return self.consumer_tag
The consumer tag will only be returned when the application gets stopped manually or after crashing. The consumer tag is irrelevant at that moment. I think the logging should be moved inside this method as I don't see a method to return the consumertag from within the `While True:` loop.

You can see this here where I started the application and it logs the first line, but only after pressing ctrl-c (KeyboardInterupt) it prints the second line with the consumertag:

`python main.py                                                                                                                                                                                                                          
{"message": "Waiting for messages on queue vrt.events.essence...", "logger": "app.app", "level": "info", "timestamp": "2021-02-19T14:10:25.357593Z", "source": "/home/rudolf/stack/viaa/projects/vrt-events-essence/app/app.py:start:497"}
^C{"message": "Consumer tag is: ctag2.63b9f6248220445cbc26129adc27b6fd...", "logger": "app.app", "level": "info", "timestamp": "2021-02-19T14:10:28.213758Z", "source": "/home/rudolf/stack/viaa/projects/vrt-events-essence/app/app.py:start:499"}
`

2021-02-24 14:55 UTC, DriesDD commented
@RudolfDG Thanks, the unit tests didn't catch that. Moved the logging inside rabbit.py
I am not sure how I could write a test for something that happens in the RabbitClient, if you have an idea, feel free to share.

2021-04-12 06:20 UTC, maartends requested changes
Repo now contains both:

- config.yml
- config.yml.example

Remove either one.

2026-08-18 09:16 UTC, spacid commented
@maartends Can I close this PR and remove the branch?

2026-08-21 12:06 UTC, merged